sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."

install:
  - composer update -n --prefer-dist
  - travis/install-eio.sh
  - travis/install-uv.sh
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - chmod +x coveralls.phar

script:
    # PHPDBG segfaults on versions other than 7.0 currently
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then
      phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml;
    else
      vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml;
    fi
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then ./coveralls.phar; fi

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local
